# TravisCI configuration for php-stubs/genesis-stubs

language: "php"
os:
  - "linux"
dist: "bionic"

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  # giacocorsiglia/stubs-generator does not support PHP 7.0

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer validate --strict"

install:
  - "wget --content-disposition -P source 'https://my.studiopress.com/?download_id=91046d629e74d525b3f2978e404e7ffa'"
  - "unzip -d source source/genesis.*.zip"
  - "composer update --no-interaction --no-suggest"

script:
  - "bash -x ./generate.sh"
  - "php -l genesis-stubs.php"
  - "git diff --exit-code"
  - |
    php -r 'require "vendor/php-stubs/wordpress-stubs/wordpress-stubs.php"; require "genesis-stubs.php";'
